### ISSUE TITLE
XHTML Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [gsegol/sinclair-lewis_babbitt#1]
_This list only focuses on changes needed in the xhtml files._

Misc.:

- [x] Upgrade your toolset by running `pipx upgrade standardebooks`. Afterwards when you run `se lint` again, you will see new errors. These will go away when you run `se clean` again. Commit those changes.

- [x] Run `se modernize-spelling .` Double check the changes before committing.

- [x] Remove all of the `para1` ids from the chapters. We don't want these.

Chapter 1:

- [ ] Remove the `<span epub:type="z3998:roman">` in the B.V.D.s.

- [x] In "White piping on the V of the vest..." the V should be lower cased, italicized and tagged as a grapheme.

Chapter 2:

- [x] The last `<blockquote>` doesn't quite match the page scans. It would look better if you structured it like:
```
				<blockquote>
					<p>Ashtabula Street, 496⁠—<abbr epub:type="z3998:given-name">J. K.</abbr> Dawson to</p>
					<p>Thomas Mullally, April 17, 15.7 × 112.2,</p>
					<p><abbr>mtg.</abbr> $4,000……………………………<abbr class="eoc">Nom.</abbr></p>
				</blockquote>

```

Chapter 3:

- [x] `<strong>` is meant for strong emphasis, but this is not the case in this chapter. Convert the `<strong>`s into `<b>`s.

- [x] The addresses should be tagged with `<p epub:type="se:letter.dateline">`.

- [x] The `z3998:sender` and `z3998:recipient` semantics are only applied to names. Surround Babbitt-Thompson Realty Co. with `<span epub:type="z3998:sender">` and Omar Gribble with `<span epub:type="z3998:recipient">`.

- [x] You don't need the `<br/>`s that are before the addresses.

- [x] "CO." should be "Co." in Babbitt-Thompson Realty Co.

- [x] In the letter, remove the left double quote at the beginning of “He is perfectly willing to pro rate..."

- [x] "Say, old man!" is in a separate paragraph.

- [x] The valediction, postscript, and following paragraphs need to be inside a `<footer>`.

- [ ] Tag the paragraphs after P.S. with `epub:type="z3998:postscript"`.

- [ ] In "Oh, no, ‘tain’t a question..." the first single quote is in the wrong direction.

- [x] Remove the `<span epub:type="z3998:roman">` in a.m.i.

Chapter 4:

- [x] Convert the `<strong>`s into `<b>`s.

- [x] "Do You Respect Your Loved Ones?" is a title, so it goes inside a `<header>` and is titlecased.

- [x] "Sole agents Babbitt-Thompson Realty Company Reeves Building" goes in a `<footer>`.

- [x] "IS" needs to be in lowercase and surrounded with `<strong>`.

- [x] The paragraph beginning with "Do you get it?..." needs a left double quote.

Chapter 5:

- [x] A grapheme is a unit (such as a letter or digraph) of a writing system. What you have are phrases that are italicized. Just use `<em>`s for those.

Chapter 6:

- [x] Everything from "Power and Prosperity in Public Speaking" to "Are You a 100 Percenter or a 10 Percenter?" should be in a `<blockquote>`.

- [x] Remove the `<blockquote>` that's containing "Here’s how it happened. I ran across an ad..."

- [x] "Power and Prosperity in Public Speaking" and "A Yarn Told at the Club" are header elements, so they go inside a `<header>`.

- [x] The `<div>`s should be converted into `<blockquote>`s.

- [x] "What We Teach You" and "Prof. W. F. Peet" are titles for the mini ads, so they go inside a `<header>`.

- [x] Everything from "Shortcut Educational Pub. Co." to "Are You a 100 Percenter or a 10 Percenter?" belongs in a `<footer>`.

- [x] "Desk WA" and "Sandpit, Iowa." appear on the same line with a gap. With some tricky CSS, we can get it to look pretty similar, but it needs to be structured like the following in order to work.
```
					<p>
						<span>Desk WA</span>
						<span>Sandpit, Iowa.</span>
					</p>
```
Yes, lint will complain, but most works don't require such complex styling!

- [x] I think WA is supposed to be the abbreviation for the State of Washington and should be tagged with `<abbr epub:type="z3998:place">`.

- [x] "Can You Play a Man’s Part?" is a title, so it goes inside a `<header>`.

- [x] "Did" in “But gooooooosh, Dad, if they <em>did</em>!” is in small-caps in the page scans.

- [x] "MY" needs to be in lowercase and surrounded with `<strong>`.

- [x] There's a typo in "NO SPECIAL EDUACTION REQUIRED."

- [x] "YOU", "PROFESSION", "MONEY", "BIG", and "NO SPECIAL EDUCATION REQUIRED" need to be in lowercase and surrounded with `<strong>`s.

Chapter 8:

- [x] Remove the `<span epub:type="z3998:roman">` in B.V.D.

- [x] Remove the `<span epub:type="z3998:roman">` in f-i-f-t-y

Chapter 9:

- [x] There are Chemical formulas for rubber and isoprene. See [SEMOS 8.12](https://standardebooks.org/manual/1.6.3/single-page#8.12) on how to format these.

- [x] "Buena giorna, señor, com sa va, wie geht’s? Keskersaykersa a little pome, señor?" needs language tags ([SEMOS 8.2.9](https://standardebooks.org/manual/1.6.3/single-page#8.2.9)).

- [x] Think the **i** in "That’s the i.!" is suppose to be a roman numeral. Make sure it is receives semantics, and remove the period.

Chapter 13:

- [x] The image needs semantics. Take a look at the examples in [SEMOS 7.8.5.4](https://standardebooks.org/manual/1.6.3/single-page#7.8.5.4).

- [x] You're missing poem indents. Check [page 161](https://archive.org/details/babbitt00lewiuoft/page/161/mode/1up) to see where to add `class="i1"` for indents.

- [x] Everything from "Old Colony Theatre" to "...Listen to what the Hep Bird twitters." should be inside one `<blockquote>`. Remove the other `<blockquote>`s. One advertisement = one `<blockquote>`.

- [x] Everything from "Old Colony Theatre" to "Oh, Gee, Kids." goes inside a `<header>`.

- [x] "Old Colony Theatre" is a title. Just put it in its own `<p>`.

- [x] "Shake the Old Dogs to the..." is not a poem. You can structure it like:
```
					<p>Shake the Old Dogs to the<br/>
					<b>Wrollicking Wrens</b><br/>
					The bonniest bevy of beauteous<br/>
					bathing babes in burlesque.<br/>
					Pete Menutti and his<br/>
					Oh, Gee, Kids.</p>
```

- [x] There is an abbreviation in "...the PDQest show ever." 

- [x] In "And a-noth-er drink wouldn’ do ’s ‘ny harmmmmmmm." the third single quote is in the wrong direction.

Chapter 14:

- [x] The clipping beginning with "When I am out upon the road..." should be in a `<blockquote>`.

- [ ] Remove the italics that are outside of the `<p>`s. Epub check does not like that. You can use `<q>`s inside of the paragraphs.

Chapter 15:

- [x] "Tickler No. 3" is a title, so it goes in a `<header>`. Convert `<strong>` in to `<b>`.

Chapter 21:

- [x] "Service and Boosterism" goes in a `<header>`. Convert `<strong>` in to `<b>`.

- [x] Everything from "Dad Petersen" to “Ads, not Fads, at Dad’s.” goes in a `<footer>`.

Chapter 27:

- [x] "ALL" needs to be in lowercase and surrounded with `<strong>`.

- [x] "KNOW" needs to be in lowercase and surrounded with `<strong>`.

Chapter 28:

- [x] "WILL" needs to be in lowercase and surrounded with `<strong>`.

Chapter 31:

- [x] "MADE" needs to be in lowercase and surrounded with `<strong>`.

- [x] "YOU" needs to be in lowercase and surrounded with `<strong>`.

- [x] "MUST" needs to be in lowercase and surrounded with `<strong>`.

Chapter 32:

- [x] "THE" needs to be in lowercase and surrounded with `<strong>`.

Chapter 34:

- [x] "ALL" needs to be in lowercase and surrounded with `<strong>`.

After All the Changes:

- [x] Make sure to run `clean`, `typogrify`, and `semanticate` again. Double check the changes before committing.

**Comment by EmmaSweeney** [comment]
**Additional Issues**

Chapter 6:

- [x] Convert the `<strong>` to `<b>` that is around "Can You Play a Man’s Part?".

Chapter 13:

- [x] You're missing a `<br/>` after the line `<span class="i1">We blithely sing</span>`.

- [x] Remove the extra > from `<span class="i1">>Oh, here we come,</span>`.

Chapter 15:

- [x] I missed this the first time. P.D.Q. needs `<abbr epub:type="z3998:initialism">`.

Chapter 28:

- [x] You're missing a space after `<strong>will</strong>`.

After changes:

- [x] Run `clean` again.

**Clarifications**

- _The addresses should be tagged with `<p epub:type="se:letter.dateline">`._
You've tagged the first address but not the second.

- _In the letter, remove the left double quote at the beginning of “He is perfectly willing to pro rate..."_
The one on line 92. This will clear the t-003 error.

- _In "Oh, no, ‘tain’t a question..." the first single quote is in the wrong direction._
Look at single quote in **‘tain’t**

- _Think the i in "That’s the i.!" is suppose to be a roman numeral. Make sure it is receives semantics, and remove the period._
You've tagged it correctly but still need to remove the period.

- _The image needs semantics. Take a look at the examples in [SEMOS 7.8.5.4](https://standardebooks.org/manual/1.6.3/single-page#7.8.5.4)._
...more specifically [SEMOS 7.8.3](https://standardebooks.org/manual/1.6.3/7-high-level-structural-patterns#7.8.3) and [SEMOS 7.8.4](https://standardebooks.org/manual/1.6.3/7-high-level-structural-patterns#7.8.4) semantics. These appear at the end of the `<img/>` elements in the examples.

- _"Old Colony Theatre" is a title. Just put it in its own `<p>`._
You don't need the `<span>`s.

- _There is an abbreviation in "...the PDQest show ever."_
Are these name initials? If so, see [SEMOS 8.10.4 ](https://standardebooks.org/manual/1.6.3/single-page#8.10.4)on how to format this correctly and lint should stop complaining. There is another "P.D.Q." somewhere in this book that needs to receive the same treatment.

- _Remove the italics that are outside of the `<p>`s. Epub check does not like that. You can use `<q>`s inside of the paragraphs._
You can't have paragraphs inside paragraphs. The `<q>`s go inside each paragraph like so:
```
					<p>
						<q>When I am out upon the road...</q>
					</p>

```
