### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [gsegol/sinclair-lewis_babbitt#3]
Chapter 1:

- [x] Remove the `<span epub:type="z3998:roman">` in the two B.V.D.s.

Chapter 3:

- [x] `<abbr epub:type="z3998:initialism">P.S.</abbr>` needs to be inside of the `<p epub:type="z3998:postscript">`.  It should look like the postscript in the first example after [SEMOS 7.7.3.5.1](https://standardebooks.org/manual/1.6.3/7-high-level-structural-patterns#7.7.3.5.1).

- [x] Tag the two paragraphs after the postscript with `epub:type="z3998:postscript"`. This will allow the CSS to make the paragraphs look like the page scans.

- [x] `‘tain’t` in "Oh, no, ‘tain’t a question..." needs to be `’tain’t` ([SEMOS 8.7.5.3](https://standardebooks.org/manual/1.6.3/single-page#8.7.5.3)).

- [x] Remove the `<b>` around `Babbitt-Thompson Realty <abbr class="eoc">Co.</abbr>`. The CSS will take care of the small caps.

- [x] Add `<br/>`s after `<span epub:type="z3998:sender">Babbitt-Thompson Realty <abbr class="eoc">Co.</abbr></span>` and `<span epub:type="z3998:recipient">Omar Gribble, <abbr>Esq.</abbr></span>,` to match the addresses in the page scans.

- [x] Move `epub:type="z3998:salutation"` to the `<p>` surrounding "Say, old man!" It should look like the salutation in the first example after [SEMOS 7.7.3.5.1](https://standardebooks.org/manual/1.6.3/7-high-level-structural-patterns#7.7.3.5.1).

- [x] Remove the `<b>` around "Say, old man!" The CSS will take care of the small caps.

Chapter 6:

- [x] "What We Teach You" is missing an exclamation point.

- [x] After working with the CSS, it will make things easier by removing the `<b>`s around the headers "What We Teach You!" and "Prof. W. F. Peet". The CSS will take care of the small caps.

- [x] After working with the CSS, It would be best to move the mini ad titled "What We Teach You!" to the top of the large advertisement. It will be located before the paragraph `<p>Who do you think I ran into the other evening...` in order for the mini ad to float left of the first two paragraphs.

- [x] Remove `&gt;` inside `<strong>profession</strong>`.

- [x] Add a space after `<strong>profession</strong>`.

Chapter 9:

- [x] `U.` in `we learned about him in the U.,` needs to be tagged as `<abbr epub:type="z3998:initialism">`.

Chapter 13:

- [x] I recommend removing `class="half-page"` from the `<figure>`. The image contains tiny details, and we want the small e-readers to display the image as large as possible.

- [x] The image is missing the `se:image.color-depth.black-on-transparent` semantic. The image is line art with a transparent background. This is important because this SVG can be inverted in dark mode so that it is visible on black/dark backgrounds.

Chapter 14:

- [x] `<q>` is an inline element that cannot surround block-level elements like `<p>`. You can't have paragraphs inside paragraphs. The `<q>`s go inside each paragraph. This issue will have been successfully corrected when you don't receive any errors from `se build --check-only .` Right now it gives you three RSC-005 errors.
```
				<blockquote>
					<p>
						<q>When I am out upon the road... who savvy whom I am!</q>
					</p>
					<p>
						<q>But when I get that lonely spell... in my home town!</q>
					</p>
					<p>
						<q>Then when I entered that hotel... home sweet home.</q>
					</p>
				</blockquote>
```

Chapter 15:

- [x] `U.` in `Who, who? The U.!` needs to be tagged as `<abbr epub:type="z3998:initialism">`.

Chapter 21:

- [x] Remove the `z3998:sender` from "Dad Petersen." This isn't a letter.

Chapter 26:

- [x] `I. W. W.` needs to be tagged as an abbreviation. Found in "Babbitt had always supposed that Doane associated only with the I. W. W." 

Chapter 32:

- [x] `G.C.L.` needs to be tagged as `<abbr epub:type="z3998:initialism">`.

Chapter 34:

- [x] `U.` in `you could go right ahead with the U.,` needs to be tagged as `<abbr epub:type="z3998:initialism">`.

se-lint-ignore.xml:

- [x] Ignore lint error s-046 in Chapter 6. The two clauses are being separated with CSS.

content.opf:

- [x] The short description needs to be a complete sentence.

local.css

- [x] Replace everything in the file with the following CSS.
```
@charset "utf-8";
@namespace epub "http://www.idpf.org/2007/ops";
@namespace xml "http://www.w3.org/XML/1998/namespace";

body [xml|lang],
q{
	font-style: italic;
}

section{
	break-after: page;
}

/* Letter */
[epub|type~="z3998:letter"] header{
	text-align: right;
}

[epub|type~="z3998:letter"] header p + p{
	margin-top: 1em;
}

#chapter-3 [epub|type~="z3998:letter"] header > p[epub|type~="se:letter.dateline"]:nth-of-type(2),
#chapter-3 [epub|type~="z3998:letter"] header > [epub|type~="z3998:salutation"]{
	text-align: initial;
}

[epub|type~="z3998:letter"] footer{
	margin-top: 1em;
	text-align: right;
}

[epub|type~="z3998:salutation"] + p,
[epub|type~="z3998:letter"] header + p{
	text-indent: 0;
}

[epub|type~="z3998:sender"],
[epub|type~="z3998:recipient"],
[epub|type~="z3998:salutation"],
[epub|type~="z3998:signature"]{
	font-variant: small-caps;
}

[epub|type~="z3998:postscript"]{
	margin-top: 1em;
	text-align: initial;
	text-indent: 0;
}
/* End letter */

/* Poem */
[epub|type~="z3998:poem"] p{
	text-align: initial;
	text-indent: 0;
}

[epub|type~="z3998:poem"] p > span{
	display: block;
	padding-left: 1em;
	text-indent: -1em;
}

[epub|type~="z3998:poem"] p > span + br{
	display: none;
}

p span.i1{
	padding-left: 2em;
	text-indent: -1em;
}
/* End poem */

/* Image */
figure{
	break-inside: avoid;
	margin: 1em auto;
	text-align: center;
}

figure img{
	display: block;
	margin: auto;
	max-width: 100%;
}
/* End image */

/* Blockquote */
header,
footer{
	margin: 1em;
	text-align: center;
}

header p,
footer p{
	text-indent: 0;
}

#chapter-4-2 blockquote p:nth-of-type(2){
	margin: 1em;
	text-align: center;
	text-indent: 0;
}

#chapter-13 header p + p{
	margin-top: 1em;
}

#chapter-21 [epub|type~="z3998:signature"]{
	margin-bottom: 1em;
	text-align: right;
}
/* End blockquote */

/* Large advertisement (chapter 6) */
#chapter-6-3 > blockquote:first-of-type{
	margin: 1em 0;
}

#chapter-6-3 > blockquote:first-of-type > header::before{
	content: "$ $ $ $ $ $ $ $ $";
	display: block;
	font-weight: bold;
	margin-bottom: 1em;
	text-align: center;
}

#chapter-6-3 > blockquote:first-of-type > header p + p{
	margin-top: 1em;
}

#chapter-6-3 > blockquote:first-of-type header p b,
#chapter-6-3 > blockquote:first-of-type footer p b{
	text-transform: uppercase;
}

#chapter-6-3 footer > p:first-child{
	font-variant: small-caps;
}

#chapter-6-3 footer > p:last-child{
	margin-top: 1em;
}

#chapter-6-3 footer p > span:first-child{
	padding-right: 4em;
}

#chapter-6-3 blockquote blockquote{
	border: 2px solid;
	height: auto;
	margin: 1em;
	padding: 1em;
	width: 200px;
}

#chapter-6-3 blockquote blockquote header{
	font-variant: small-caps;
}

#chapter-6-3 blockquote blockquote p{
	text-indent: 0;
}

#chapter-6-3 blockquote blockquote:first-of-type{
	float: left;
}

#chapter-6-3 blockquote blockquote:last-of-type{
	float: right;
}

#chapter-6-3 footer{
	clear: both;
}
/* End large advertisement (chapter 6) */
```

After All of the Changes:

- [x] Run `se clean .` again.

- [x] Run `se typogrify .` again.

- [x] When running `se find-mismatched-dashes .`, there are a couple words with mismatching dashes. These look like they can be normalized throughout the book. These changes would need to go into an editorial commit.
